{print} = require 'sys'
{exec}  = require 'child_process'

Rehab   = require '../node_modules/rehab/lib/rehab'


task 'build', 'Build coffee2js using Rehab', sbuild = ->
    console.log "Building project from app/*.coffee to bin/app.js"

    files = new Rehab().process './app'

    to_single_file = "--join bin/app.js"
    from_files = "--compile --watch #{files.join ' '}"

    # exec "coffee #{to_single_file} #{from_files}", (err, stdout, stderr) ->
    #     throw err if err

    coffee = exec "coffee #{to_single_file} #{from_files}"
    coffee.stderr.on 'data', (data) ->
        process.stderr.write data.toString()
    coffee.stdout.on 'data', (data) ->
        print data.toString()
    coffee.on 'exit', (code) ->
        callback?() if code is 0
